// Mega-menu task types organized into columns (poster-facing)
export const posterTaskTypes: string[][] = [
   [
      "Accountant",
      "Admin Assistant",
      "Appliance Repair",
      "Architect",
      "Auto Electrician",
      "AV Specialist",
      "Barista",
      "Bartender",
      "Bricklayer",
      "Cabinet Maker",
      "Car Wash",
      "Carpenter",
      "Carpet Cleaner",
      "Caterer",
      "Chef",
      "Cleaner",
      "Clothing Alteration",
      "Commercial Cleaner",
      "Concreter",
      "Cooking",
      "Copywriter",
      "Courier Services",
   ],
   [
      "Data Entry Specialist",
      "Decking",
      "Delivery",
      "Designer",
      "Digital Design",
      "Drafting",
      "Driving",
      "End Of Lease Cleaner",
      "Engraving",
      "Entertainment",
      "Events Staff",
      "Fencing",
      "Flooring",
      "Food Delivery",
      "Furniture Assembler",
      "Gardener",
      "General Labour",
      "Graffiti Artist",
      "Grocery Delivery",
      "Handyman",
      "HIIT Trainer",
   ],
   [
      "House Cleaner",
      "Housekeeper",
      "Interior Designer",
      "IT Support",
      "Landscaper",
      "Locksmith",
      "Logo Designer",
      "Makeup Artist",
      "Marketing",
      "Mechanic",
      "Mobile Bike Repair",
      "Office Cleaner",
      "Painter",
      "Paver",
      "Pest Controller",
      "Pet Groomer",
      "Pet Minder",
      "Pilates Instructor",
      "Plasterer",
      "Project Management",
      "Proofreader",
   ],
   [
      "Property Maintenance",
      "Receptionist",
      "Removalist",
      "Research Assistant",
      "Resume Writer",
      "Roofing",
      "Rubbish Removal",
      "Tradesman",
      "Translator",
      "Turf Laying",
      "Tutor",
      "Virtual Assistant",
      "Wait Staff",
      "Waterproofing",
      "Web Design & Developer",
      "Wedding Services",
      "Window Cleaner",
      "Yoga Instructor",
   ],
];

// Tasker-facing categories now use the full list for parity with posters.
export const taskerTaskTypes: string[][] = posterTaskTypes;

// Backward compatibility alias
export const taskTypes = posterTaskTypes;