// Mega-menu task types organized into columns for Taskers (people looking for work)
export const taskerTypes: string[][] = [
   [
      "Appliance Repair",
      "Auto Electrician",
      "Bricklayer",
      "Cabinet Maker",
      "Carpenter",
      "Carpet Cleaner",
      "Cleaner",
      "Commercial Cleaner",
   ],
   [
      "Concreter",
      "Decking",
      "End Of Lease Cleaner",
      "Fencing",
      "Flooring",
      "Furniture Assembler",
      "Gardener",
      "General Labour",
   ],
   [
      "House Cleaner",
      "Housekeeper",
      "Landscaper",
      "Locksmith",
      "Mechanic",
      "Mobile Bike Repair",
      "Office Cleaner",
      "Painter",
   ],
   [
      "Paver",
      "Pest Controller",
      "Plasterer",
      "Property Maintenance",
      "Removalist",
      "Roofing",
      "Rubbish Removal",
      "Tradesman",
      "Turf Laying",
      "Waterproofing",
      "Window Cleaner",
      "Car Wash",
   ],
];

// Mega-menu task types organized into columns for Posters (people hiring services)
export const posterTypes: string[][] = [
   [
      "Accountant",
      "Admin Assistant",
      "Architect",
      "AV Specialist",
      "Data Entry Specialist",
      "Designer",
      "Digital Design",
      "Drafting",
      "Logo Designer",
      "Interior Designer",
      "Marketing",
      "Project Management",
      "Copywriter",
      "Proofreader",
      "Content Writer",
   ],
   [
      "IT Support",
      "Web Design & Developer",
      "Virtual Assistant",
      "Research Assistant",
      "Resume Writer",
      "Translator",
      "Information Technology",
      "Business Consulting",
      "Financial Advisor",
      "Tax Specialist",
      "Legal Consultant",
      "Human Resources",
      "Event Planning",
      "Photography",
   ],
   [
      "HIIT Trainer",
      "Pilates Instructor",
      "Yoga Instructor",
      "Personal Training",
      "Nutrition Coaching",
      "Makeup Artist",
      "Pet Groomer",
      "Pet Minder",
      "Tutor",
      "General Teaching",
      "Music Lessons",
      "Language Coaching",
      "Mentor",
   ],
   [
      "Courier Services",
      "Delivery",
      "Moving Services",
      "Storage Solutions",
      "Graffiti Artist",
      "Wedding Services",
      "Party Planning",
      "Entertainment Services",
      "Photography",
      "Videography",
      "Graphic Design",
   ],
];

// Legacy export for backward compatibility
export const taskTypes: string[][] = [
   [
      "Accountant",
      "Admin Assistant",
      "Appliance Repair",
      "Architect",
      "Auto Electrician",
      "AV Specialist",
      "Barista",
      "Bartender",
      "Bricklayer",
      "Cabinet Maker",
      "Car Wash",
      "Carpenter",
      "Carpet Cleaner",
      "Caterer",
      "Chef",
      "Cleaner",
      "Clothing Alteration",
      "Commercial Cleaner",
      "Concreter",
      "Cooking",
      "Copywriter",
      "Courier Services",
   ],
   [
      "Data Entry Specialist",
      "Decking",
      "Delivery",
      "Designer",
      "Digital Design",
      "Drafting",
      "Driving",
      "End Of Lease Cleaner",
      "Engraving",
      "Entertainment",
      "Events Staff",
      "Fencing",
      "Flooring",
      "Food Delivery",
      "Furniture Assembler",
      "Gardener",
      "General Labour",
      "Graffiti Artist",
      "Grocery Delivery",
      "Handyman",
      "HIIT Trainer",
   ],
   [
      "House Cleaner",
      "Housekeeper",
      "Interior Designer",
      "IT Support",
      "Landscaper",
      "Locksmith",
      "Logo Designer",
      "Makeup Artist",
      "Marketing",
      "Mechanic",
      "Mobile Bike Repair",
      "Office Cleaner",
      "Painter",
      "Paver",
      "Pest Controller",
      "Pet Groomer",
      "Pet Minder",
      "Pilates Instructor",
      "Plasterer",
      "Project Management",
      "Proofreader",
   ],
   [
      "Property Maintenance",
      "Receptionist",
      "Removalist",
      "Research Assistant",
      "Resume Writer",
      "Roofing",
      "Rubbish Removal",
      "Tradesman",
      "Translator",
      "Turf Laying",
      "Tutor",
      "Virtual Assistant",
      "Wait Staff",
      "Waterproofing",
      "Web Design & Developer",
      "Wedding Services",
      "Window Cleaner",
      "Yoga Instructor",
   ],
];